### ISSUE TITLE
googleapis.com - A Django RESTAPI for Google-Code In

### ISSUE THREAD

**Issue by KVGarg** [googleapis/googleapis.github.io#10]
In context to [Google-Code In](https://gitlab.com/GoogleCodeIn/api), currently python requests are used to make API calls to query the results ,so  is there any possibility of creating the API an install-able package so that other organizations can install that package using python and work with it. 
If there is a requirement, I would like to take this as a GSoC'19 initiative.

**Comment by lukesneeringer** [comment]
Hi @KVGarg,
Thanks for your inquiry. I am our local Python guy, but I am not sure sure what you are proposing. Could you elaborate further so we can route this?

**Comment by KVGarg** [comment]
Hi, @lukesneeringer Currently I'm working with the coala organization and we're having a community website that shows the contributors who have participated in GCI with our organization. And there might be other organizations as well who might be showing GCI related data.
And all these organizations currently use Python requests to query GCI data. Like we use [PyGithub](https://github.com/PyGithub/PyGithub) to make GitHub API calls instead of directly using python requests, I was thinking of a similar idea to implement a PyPi installable package so that open source communities can use it much easier with an increase in portability.

**Comment by lukesneeringer** [comment]
We create these already. github.com/googleapis/google-cloud-python :-)

**Comment by KVGarg** [comment]
Can you help me out how to query GCI APIs? Are there any docs or examples that show how to query GCI data using google-cloud-python!
