### ISSUE TITLE
[GSoC] Query about project idea

### ISSUE THREAD

**Issue by Parth-Vader** [googleapis/googleapis.github.io#11]
I am interested in the project idea `Build tools that bridge OpenAPI and gRPC`, and wanted to know some more details about it. Here are my questions:-

1) Are all three points required to be tackled in the project?
2) Are the OpenAPI descriptions required in the gRPC APIs should be for each field? I'm a bit unclear about this.
3) How would the points 2 and 3 be tackled? From what I understand, gRPC’s HTTP/JSON Transcoding would be used to serve a gRPC API as a REST API via istio proxy. How would the checking be done for an OpenAPI description?

**Comment by timburks** [comment]
Hi, thanks for reaching out! Please send your GSOC questions to actools-info@google.com and our team will follow up with you there.
