### ISSUE TITLE
actools-info email failure

### ISSUE THREAD

**Issue by ChanForPres** [googleapis/googleapis.github.io#13]
(Tried emailing about GSOC 2019)

Hi,
My name is Marcus, would be interesting in designing and implementing an improved surface for the Java GRPC client library. Have ideas on using the Util.concurrent.future library combined with an ExecutorService. Please provide link to stay in touch with GSOC mentors and get program updates.

For more information, please refer to my website: https://chanforpres.github.io/
Would be happy to answer any questions that may arise. 
Thank you!

**Comment by timburks** [comment]
Hi Marcus,

Please email us at actools-info@google.com - we had some initial configuration problems but it is accepting emails now and we will follow up with you there.

Tim
