### ISSUE TITLE
GSoC 2019

### ISSUE THREAD

**Issue by rmeena840** [googleapis/googleapis.github.io#15]
Hi,
I am undergraduate student pursuing B.Tech in Computer Science from IIT Dhanbad. I am GSoC 2019 aspirant. I was exploring the GSoC projects and I am interested in the following project "Prototype and implement better API client libraries". Please share the relevant link to setup development environment and also community group link to discuss the project.
Thanks
--Ravindra Kumar Meena

**Comment by timburks** [comment]
Hi, thanks for reaching out! Please send your GSOC questions to actools-info@google.com and our team will follow up with you there.
