### ISSUE TITLE
gRPC protocol detection fails for services at *.googleapis.com

### ISSUE THREAD

**Issue by vmagamedov** [googleapis/googleapis.github.io#27]
Hi! I'm using [third-party gRPC library](https://github.com/vmagamedov/grpclib) to work with Speech-to-Text API and I'm getting 404 HTTP errors from Google servers. Request looks like this:
```
:authority: speech.googleapis.com:443
:path: /google.cloud.speech.v1.Speech/Recognize
content-type: application/grpc+proto
```
And it turns out that if you send gRPC request with `content-type: application/grpc+proto`, your request is not detected as a gRPC call and you get 404 error. If you send `content-type: application/grpc` – everything works fine.

See https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md. It is totally correct to send `application/grpc+proto`.

Related issue: https://github.com/vmagamedov/grpclib/issues/84

It would be great to fix this and support both content-type header values as described in the protocol spec.

And here is how to reproduce this issue:
```console
$ curl -v -XPOST -H 'content-type: application/grpc' --http2 --http2-prior-knowledge https://speech.googleapis.com/google.cloud.speech.v1.Speech/Recognize 2>&1 | grep -e '^< '
< HTTP/2 200
< content-type: application/grpc
< date: Wed, 15 Jan 2020 10:11:25 GMT
< alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000

$ curl -v -XPOST -H 'content-type: application/grpc+proto' --http2 --http2-prior-knowledge https://speech.googleapis.com/google.cloud.speech.v1.Speech/Recognize 2>&1 | grep -e '^< '
< HTTP/2 404
< date: Wed, 15 Jan 2020 10:10:54 GMT
< content-type: text/html; charset=UTF-8
< server: ESF
< content-length: 1600
< x-xss-protection: 0
< x-frame-options: SAMEORIGIN
< x-content-type-options: nosniff
< alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
```

**Comment by wenbozhu** [comment]
This is indeed a (server-side) implementation issue that violates the spec. We will fix the underlying issue and post an update here as soon as the fix is rolled out. 

Thanks.

**Comment by jamesthompson** [comment]
@wenbozhu Please could you clarify the exact headers required and the exact encodings expected and their representations as well? I get 200s but I always see the `Request contains an invalid argument.` grpc-message returned on the response for a well-formed gzipped proto-encoded request data input. 

The exact same request works fine with the java SDK, but I can't make it work with a hand-rolled implementation.

**Comment by jamesthompson** [comment]
For those interested - it seems that the request body must *NOT* be gzipped, that is to say the `"grpc-encoding"` is `identity` (note - this is elided by the client lib generated by google for java), but the canonical return body is indeed gzipped when the `"grpc-accept-encoding"` header is set to `"gzip"`.

Wonderful though it is to be able to hit these gRPC apis, I think the documentation could do with more clarity for the happy path for gPRC - not just the RPC fallback over HTTP 1.1.

**Comment by JustinBeckwith** [comment]
Closing out since this appears to be resolved

**Comment by vmagamedov** [comment]
@JustinBeckwith please try two my curl commands I posted above to reproduce this issue, I still see different responses:
- `200` for `content-type: application/grpc`, which is OK, this response from gRPC server
- `404` for `content-type: application/grpc+proto`, which is not OK, this response from REST server
