### ISSUE TITLE
Sheets API / Get Image from Cell

### ISSUE THREAD

**Issue by pljspahn** [googleapis/googleapis.github.io#28]
Since it is possible to insert and image into a cell from the Sheets web interface, will it be possible to add the retrieval of this image via the Sheets API, such as adding a `valueRenderOption` of `IMAGE` to `sheets.spreadsheets.values.get()`?

**Comment by JustinBeckwith** [comment]
Greetings!  This isn't really a repository where we can help answer question like that :/  I would suggest checking out one of the links here:
https://developers.google.com/sheets/api/support
