### ISSUE TITLE
Feature Request:  Provide an Android Publisher API that allows managing the Email List for Closed Betas

### ISSUE THREAD

**Issue by noelstieglitz** [googleapis/googleapis.github.io#30]
I originally asked [this ](https://stackoverflow.com/questions/57698409/is-it-possible-to-manage-the-google-play-console-email-list-programmatically-via) on StackOverflow, but later opened an issue on the Google API Python Client repository.  However, that is wrong place, as it seems that the API itself is not available for the client SDKs to consume.  Another user opened a similar issue under the node client repo (linked below).

I'd love a way to manage the email list that controls who has access to an app that is in a Closed Android ~Beta~ Alpha Track.  This is the email list:

![](https://i.stack.imgur.com/BPBMT.png)

The only existing related API I could find allowed managing the Google Groups or Google+ communities associated with Closed Builds, but that doesn't allow controlling the specific users.  It appears the functionality in the Play Store changed, but the API was never updated to reflect the newer way of managing Closed Alpha users.

Here are some related requests:
https://github.com/googleapis/google-api-nodejs-client/issues/1092
https://github.com/googleapis/google-api-python-client/issues/756
https://issuetracker.google.com/issues/78809407

I was referred to the "Google Play Developer Support", but I'm not sure that's the group who is in charge of the APIs.  I did reach out twice but never heard back.  Please let me know if this is not the correct place to make this request and if you know where I should make the request.  Thanks!

**Comment by shakhal** [comment]
This is maybe stating the obvious, but, you can (theoretically) control users in the Google Group through the API.
So then you can create a Google Group, attach it to a Closed release and achieve the same functionality.

But, when I tried to add members using this API
https://developers.google.com/admin-sdk/directory/v1/guides/manage-group-members
I couldn't get it to work.

So eventually the solution was to create a Closed release attached to a Google group, 
and ask the testers to join the group so they can access release.

The link for joining a group is:
https://groups.google.com/a/[ORG NAME]i/forum/#!forum/[GROUP NAME]/join

**Comment by JustinBeckwith** [comment]
Greetings!  This isn't really a place where we're going to be able to help with an issue like that :/  If this is still an issue, I'd suggest reporting it through the Android team's tracker here:
https://issuetracker.google.com/issues/new?component=190923&template=841312
