### ISSUE TITLE
Stadia APIs?

### ISSUE THREAD

**Issue by cassidyjames** [googleapis/googleapis.github.io#39]
I came here looking for any documentation about Stadia APIs, i.e. for getting a user's profile information, avatar, friends list, game list, etc. I haven't found anything public about this, so it's entirely possible a public API does not (yet) exist. But if it does, it would be great to get it added here. If it doesn't, perhaps a note about no public APIs would save others in my situation time in the future.

**Comment by JustinBeckwith** [comment]
Greetings!  As far as we can tell, there's no public API.  Unsure if there are plans to add one :/
