### ISSUE TITLE
Which is the endpoint for AMP errors with the api of google?

### ISSUE THREAD

**Issue by JSanoja** [googleapis/googleapis.github.io#7]
Im looking a api endpoint to recieve the count errors of my amp pages, 
the same of this page https://search.google.com/search-console/amp?resource_id=##URLOFYOURSITE##

I was try the search console api but not success. I really apreciate some help, ty.

I cant found anything about amp count errors :(

**Comment by lukesneeringer** [comment]
Hi @JSanoja,
Sorry that we have been remiss about monitoring this repo.
Sadly, we do not currently cover anything with Accelerated Mobile Pages, and will need to redirect you to [AMP support](https://www.ampproject.org/support/developer/get_support).
